import { ShowEvent } from "@/types/shows";

export const UPCOMING_SHOWS: ShowEvent[] = [
  {
    id: "sp-neon",
    title: "Noite Neon",
    artist: "Luna Wave",
    venue: "Audio Club",
    city: "São Paulo, SP",
    date: "12 out 2025, 21h",
    latitude: -23.544001,
    longitude: -46.640854,
  },
  {
    id: "rj-soul",
    title: "Rio Soul Festival",
    artist: "Bruno Vibes",
    venue: "Vivo Rio",
    city: "Rio de Janeiro, RJ",
    date: "27 out 2025, 19h",
    latitude: -22.914897,
    longitude: -43.179047,
  },
  {
    id: "bh-intimo",
    title: "Acústico Íntimo",
    artist: "Sofia Campos",
    venue: "Cine Theatro Brasil",
    city: "Belo Horizonte, MG",
    date: "09 nov 2025, 20h",
    latitude: -19.919052,
    longitude: -43.937778,
  },
  {
    id: "poa-energia",
    title: "Energia do Sul",
    artist: "Grupo Aurora",
    venue: "Pepsi On Stage",
    city: "Porto Alegre, RS",
    date: "15 nov 2025, 22h",
    latitude: -29.994648,
    longitude: -51.178444,
  },
  {
    id: "ssa-praia",
    title: "Pôr do Som",
    artist: "Marina Dias",
    venue: "Farol da Barra",
    city: "Salvador, BA",
    date: "23 nov 2025, 17h",
    latitude: -13.009356,
    longitude: -38.532820,
  },
  {
    id: "pe-recife-orquestra",
    title: "Sinfonia Atlântica",
    artist: "Orquestra Recife Contemporânea",
    venue: "Teatro de Santa Isabel",
    city: "Recife, PE",
    date: "05 dez 2025, 20h",
    latitude: -8.060298,
    longitude: -34.871136,
  },
  {
    id: "pe-olinda-aurora",
    title: "Luzes de Olinda",
    artist: "Aurora Tropical",
    venue: "Alto da Sé",
    city: "Olinda, PE",
    date: "12 dez 2025, 18h",
    latitude: -7.990135,
    longitude: -34.834857,
  },
  {
    id: "pe-caruaru-forro",
    title: "Forró Nas Alturas",
    artist: "Trio Pé de Serra",
    venue: "Polo do Alto do Moura",
    city: "Caruaru, PE",
    date: "20 dez 2025, 21h",
    latitude: -8.284552,
    longitude: -35.969952,
  },
];
