import { ShowEvent } from "@/types/shows";

export const UPCOMING_SHOWS: ShowEvent[] = [
  {
    id: "sp-neon",
    title: "Noite Neon",
    artist: "Luna Wave",
    venue: "Audio Club",
    city: "São Paulo, SP",
    date: "12 out 2025, 21h",
    latitude: -23.544001,
    longitude: -46.640854,
  },
  {
    id: "rj-soul",
    title: "Rio Soul Festival",
    artist: "Bruno Vibes",
    venue: "Vivo Rio",
    city: "Rio de Janeiro, RJ",
    date: "27 out 2025, 19h",
    latitude: -22.914897,
    longitude: -43.179047,
  },
  {
    id: "bh-intimo",
    title: "Acústico Íntimo",
    artist: "Sofia Campos",
    venue: "Cine Theatro Brasil",
    city: "Belo Horizonte, MG",
    date: "09 nov 2025, 20h",
    latitude: -19.919052,
    longitude: -43.937778,
  },
  {
    id: "poa-energia",
    title: "Energia do Sul",
    artist: "Grupo Aurora",
    venue: "Pepsi On Stage",
    city: "Porto Alegre, RS",
    date: "15 nov 2025, 22h",
    latitude: -29.994648,
    longitude: -51.178444,
  },
  {
    id: "ssa-praia",
    title: "Pôr do Som",
    artist: "Marina Dias",
    venue: "Farol da Barra",
    city: "Salvador, BA",
    date: "23 nov 2025, 17h",
    latitude: -13.009356,
    longitude: -38.532820,
  },
];
